//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenteProjet.Models
{
    using System;
    using System.Web;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Article
    {
        [Key]
        public int NumArticle { get; set; }
        public string Designation { get; set; }
        public Nullable<int> PrixU { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> RefCat { get; set; }
        public string photo { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
