//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VenteProjet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Commande
    {
        [Key]
        public int NumCmd { get; set; }
        public Nullable<System.DateTime> DateCmd { get; set; }
        public Nullable<int> NumClient { get; set; }
        public Nullable<int> NumArticle { get; set; }
        public Nullable<int> QteArticle { get; set; }
        public string Designation { get; set; }
    }
}
